# Generated by Django 2.0.4 on 2019-01-24 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area31.LocationLabel', verbose_name='場所のラベル'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(help_text='Specific Departments for this user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_set', related_query_name='user', to=settings.AUTH_USER_MODEL, verbose_name='場所'),
        ),
    ]
