# Generated by Django 2.1.5 on 2019-01-31 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area31', '0006_auto_20190131_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='enter_year',
            new_name='class_of',
        ),
    ]
